def import_pods
    pod "AFNetworking"
    pod "DZReadability", :path => "../"
end

target :ios do
    platform :ios, '6.0'
    link_with 'DZReadability-iOS'
    import_pods
	pod 'MBProgressHUD'
end

target :osx do
    platform :osx, '10.8'
    link_with 'DZReadability-OSX'
    import_pods
end

