# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# before_install: cd Example && pod install && cd -
podfile: Example/Podfile
script:
- xctool test -workspace Example/DZReadability.xcworkspace -scheme DZReadability -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
