# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
podfile: Example/Podfile
script:
- xctool test -workspace Example/DZReadability.xcworkspace -scheme DZReadability -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
